"""initial schema

Revision ID: 726208d6018a
Revises:
Create Date: 2026-08-07 23:45:16.864917

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "726208d6018a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("owner", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("license", sa.JSON(), nullable=True),
        sa.Column("default_branch", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ecosystem", sa.String(length=64), nullable=True),
        sa.Column("parser_compatibility", sa.String(length=128), nullable=True),
        sa.Column("last_successful_sync", sa.DateTime(), nullable=True),
        sa.Column("sync_errors", sa.JSON(), nullable=True),
        sa.Column("skill_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repositories_ecosystem"), ["ecosystem"], unique=False)
        batch_op.create_index(batch_op.f("ix_repositories_owner"), ["owner"], unique=False)

    op.create_table(
        "skills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_key", sa.String(length=512), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("lifecycle", sa.String(length=32), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("primary_source", sa.String(length=512), nullable=True),
        sa.Column("primary_source_confidence", sa.Float(), nullable=True),
        sa.Column("primary_path", sa.String(length=1024), nullable=True),
        sa.Column("primary_path_confidence", sa.Float(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("metadata_quality", sa.String(length=32), nullable=False),
        sa.Column("version_count", sa.Integer(), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skills_canonical_key"), ["canonical_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_is_current"), ["is_current"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_lifecycle"), ["lifecycle"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_primary_source"), ["primary_source"], unique=False)

    op.create_table(
        "relationships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("rel_type", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_id", "rel_type", name="uq_relationship"),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_relationships_rel_type"), ["rel_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_target_id"), ["target_id"], unique=False)

    op.create_table(
        "repo_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.String(length=512), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=True),
        sa.Column("forks", sa.Integer(), nullable=True),
        sa.Column("open_issues", sa.Integer(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("default_branch", sa.String(length=256), nullable=True),
        sa.Column("last_push", sa.DateTime(), nullable=True),
        sa.Column("skill_count", sa.Integer(), nullable=False),
        sa.Column("release_tag", sa.String(length=256), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("repo_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repo_snapshots_repo_id"), ["repo_id"], unique=False)

    op.create_table(
        "similarities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_a_id", sa.String(length=36), nullable=False),
        sa.Column("skill_b_id", sa.String(length=36), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["skill_a_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_b_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_a_id", "skill_b_id", name="uq_similarity"),
    )
    with op.batch_alter_table("similarities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_similarities_overall_score"), ["overall_score"], unique=False)
        batch_op.create_index(batch_op.f("ix_similarities_skill_a_id"), ["skill_a_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_similarities_skill_b_id"), ["skill_b_id"], unique=False)

    op.create_table(
        "versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("source_repo", sa.String(length=512), nullable=True),
        sa.Column("source_path", sa.String(length=1024), nullable=True),
        sa.Column("source_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("source_branch", sa.String(length=256), nullable=True),
        sa.Column("source_content_hash", sa.String(length=128), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("long_description", sa.Text(), nullable=True),
        sa.Column("domain_primary", sa.String(length=256), nullable=True),
        sa.Column("domain_primary_source", sa.String(length=32), nullable=False),
        sa.Column("domain_secondary", sa.JSON(), nullable=True),
        sa.Column("input_format", sa.String(length=32), nullable=False),
        sa.Column("output_format", sa.String(length=32), nullable=False),
        sa.Column("input_json_schema", sa.JSON(), nullable=True),
        sa.Column("output_json_schema", sa.JSON(), nullable=True),
        sa.Column("input_required_fields", sa.JSON(), nullable=True),
        sa.Column("input_optional_fields", sa.JSON(), nullable=True),
        sa.Column("runtime_requirements", sa.JSON(), nullable=True),
        sa.Column("compatibility", sa.JSON(), nullable=True),
        sa.Column("install_methods", sa.JSON(), nullable=True),
        sa.Column("declared_dependencies", sa.JSON(), nullable=True),
        sa.Column("inferred_dependencies", sa.JSON(), nullable=True),
        sa.Column("quality", sa.JSON(), nullable=True),
        sa.Column("security", sa.JSON(), nullable=True),
        sa.Column("license", sa.JSON(), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("migration", sa.JSON(), nullable=True),
        sa.Column("ecosystem_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "version_id", name="uq_skill_version"),
    )
    with op.batch_alter_table("versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_versions_domain_primary"), ["domain_primary"], unique=False)
        batch_op.create_index(batch_op.f("ix_versions_skill_id"), ["skill_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_versions_source_repo"), ["source_repo"], unique=False)
        batch_op.create_index(batch_op.f("ix_versions_version_id"), ["version_id"], unique=False)

    op.create_table(
        "capabilities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id_fk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("canonical", sa.String(length=256), nullable=True),
        sa.Column("taxonomy_path", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["version_id_fk"], ["versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id_fk", "name", name="uq_version_capability"),
    )
    with op.batch_alter_table("capabilities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_capabilities_canonical"), ["canonical"], unique=False)
        batch_op.create_index(batch_op.f("ix_capabilities_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_capabilities_version_id_fk"), ["version_id_fk"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version_id_fk", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["version_id_fk"], ["versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id_fk", "name", "source", name="uq_version_tag"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_tags_version_id_fk"), ["version_id_fk"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_version_id_fk"))
        batch_op.drop_index(batch_op.f("ix_tags_name"))

    op.drop_table("tags")
    with op.batch_alter_table("capabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capabilities_version_id_fk"))
        batch_op.drop_index(batch_op.f("ix_capabilities_name"))
        batch_op.drop_index(batch_op.f("ix_capabilities_canonical"))

    op.drop_table("capabilities")
    with op.batch_alter_table("versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_versions_version_id"))
        batch_op.drop_index(batch_op.f("ix_versions_source_repo"))
        batch_op.drop_index(batch_op.f("ix_versions_skill_id"))
        batch_op.drop_index(batch_op.f("ix_versions_domain_primary"))

    op.drop_table("versions")
    with op.batch_alter_table("similarities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_similarities_skill_b_id"))
        batch_op.drop_index(batch_op.f("ix_similarities_skill_a_id"))
        batch_op.drop_index(batch_op.f("ix_similarities_overall_score"))

    op.drop_table("similarities")
    with op.batch_alter_table("repo_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repo_snapshots_repo_id"))

    op.drop_table("repo_snapshots")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationships_target_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_source_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_rel_type"))

    op.drop_table("relationships")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_primary_source"))
        batch_op.drop_index(batch_op.f("ix_skills_name"))
        batch_op.drop_index(batch_op.f("ix_skills_lifecycle"))
        batch_op.drop_index(batch_op.f("ix_skills_is_current"))
        batch_op.drop_index(batch_op.f("ix_skills_canonical_key"))

    op.drop_table("skills")
    with op.batch_alter_table("repositories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repositories_owner"))
        batch_op.drop_index(batch_op.f("ix_repositories_ecosystem"))

    op.drop_table("repositories")
    # ### end Alembic commands ###
